### ISSUE TITLE
Code doppelt?

### ISSUE THREAD

**Issue by zero-24** [astridx/adventskalender#1]
Hi,

Ist es gewollt das im view ordner:
https://github.com/astridx/adventskalender/tree/master/admin/views/

nochmal die gesamte Komponente quasie doppelt liegt?

**Comment by astridx** [comment]
Guten Morgen,

danke dir. Nein, das war nicht gewollt. Daran ist bestimmt auch Git
schuld :)

Viele Grüße
Astrid


Am 24.11.2015 um 08:51 schrieb zero-24:

**Comment by zero-24** [comment]
Ok ist aufgeräumt ;) https://github.com/astridx/adventskalender/pull/2
